### ISSUE TITLE
Critical Preview 1.0 Checklist

### ISSUE THREAD

**Issue by Lnaden** [choderalab/yank#545]
Running checklists of TODOs from a meeting today that we want to accomplish in the next week

- [x] Enable Explicit Solvent Restraints - @andrrizzi
- [x] Update YANK README.md - @lnaden
- [x] Add `yank-examples` conda-recipe - @lnaden
- [x] Add `yank-examples` after install message to meta.yaml - @lnaden
- [x] Update `yank-examples` readme's to point to website and add manifest - @lnaden
- [x] Proof and merge the examples update in online docs - @andrrizzi @jchodera 
- [x] Update online YAML docs with what is experimental, untested, broken (reaction field), and in development - @lnaden
- [x] Improve YAML commands - @andrrizzi 
- [x] Validate some number with T4 Lysozyme and a couple ligands once some bugs fixed - @lnaden @andrrizzi
- [x] Restraint validation - @jchodera
- [x] Change `softcore_beta` default in alchemy to be 0.0 by default - @andrrizzi 
- [x] Swap out T4 lysozyme `all-ligands` with minimal set of 4 ligands from Mobley paper - @andrrizzi 
- [x] YAML version - @andrrizzi 
- [x] MPI Debug
- [x] Sort out S3 docs issues with version number / development
- [x] Switch to MIT license - See #563 

Close issue when checklist complete.

**Comment by Lnaden** [comment]
This may actually be better put in the Projects than an issue come to think of it

**Comment by andrrizzi** [comment]
@Lnaden by "Improve YAML commands" you mean deprecating the unused CLI commands, or just the fix to the `restraint` and `epik` YAML syntax?

**Comment by jchodera** [comment]
Let's add "debug MPI" to that list, since this is probably a showstopper until we can resolve it.

**Comment by jchodera** [comment]
Added "Switch to MIT license" as well.

**Comment by Lnaden** [comment]
Fixed by release of 0.14.1
