### ISSUE TITLE
Site Documentation Cleanup

### ISSUE THREAD

**Issue by Lnaden** [choderalab/yank#764]
Some random site cleanup things I am noticing going through the details. Most of these are just for clarity, critically incorrect information I will open a separate issue for so they can be resolved faster.

* [x] [Harmonic Restraints](http://getyank.org/0.17.0/algorithms.html#harmonic-restraints-harmonic) have conflicting information about whether the restraint should be fully coupled or decoupled at start (#778)
* [x] [Alcehm. Intermediates](http://getyank.org/0.17.0/algorithms.html#alchemical-intermediates) have some to-do's for filling in extra details. (#778)
* [x] [Ligand rot./displacement](http://getyank.org/0.17.0/algorithms.html#metropolis-monte-carlo-displacement-and-rotation-moves) should be inform users its not on for Boresch restraints.
* [x] "Identifying equilibration and production regions.." header in Algorithms RST header indicator line (`-------` or `====` under the text) is messed up. (#778)
* [x] Auto Protocol has 2 sections which should be combined in [here](http://getyank.org/0.17.0/algorithms.html#automatic-alchemical-protocol-selection) and [here](http://getyank.org/0.17.0/algorithms.html#autotuning-the-alchemical-protocol) (#778)
* [x] Add decision flow chart for what restraint to use (#782)
* [x] Resolve #765: additional restraint option documentation, see issue for discussion (#779)

This will be an ongoing and updated issue as I (or others) find new things

**Comment by davidlmobley** [comment]
Also, is the new option for restraining to the center of a binding site in the docs yet? 

It would also be great if the really excellent stuff in the "health report" style Jupyter notebooks had either sample images of "good" and "bad" cases or links to where these could be found. (Maybe this is a separate issue). We were just using these for the first time and it wasn't totally clear to us initially what the mixing diagrams should ideally look like. After thinking about it for a while I figured it out, but I would think you'd want to make it easy for people to know whether these are "good" or "bad" or somewhere in between by providing concrete examples.

**Comment by jchodera** [comment]
> Also, is the new option for restraining to the center of a binding site in the docs yet?

I don't think so, though the feature looks like it has been added. Can you add an issue suggesting we document this capability?

> It would also be great if the really excellent stuff in the "health report" style Jupyter notebooks had either sample images of "good" and "bad" cases or links to where these could be found. (Maybe this is a separate issue). We were just using these for the first time and it wasn't totally clear to us initially what the mixing diagrams should ideally look like. After thinking about it for a while I figured it out, but I would think you'd want to make it easy for people to know whether these are "good" or "bad" or somewhere in between by providing concrete examples.

That's a great idea---create a separate issue?

> Also, what are you imagining the decision flow chart for restraints would look like?

We should also document our suggested "best practices" for this. 
* For small fragment-like molecules, we should use either `Harmonic` or `FlatBottom` to allow them to explore orientational degrees of freedom
* Currently, we don't explicitly unbias `Harmonic` to eliminate the effect of the restraint on binding sites that may be far from the center of the receptor restraint, so `FlatBottom` is probably preferred
* If you want to compute the affinity to a specific binding site, you'd probably want to define both several atoms/residues in the binding site and ligand to define the restraint. I'm not sure if you'd have to specify a spring constant rather than have it automatically computed---I think you might.
* If you want to compute the affinity to all binding sites for a macromolecule, `FlatBottom` with automatically determined parameters is probably desired
* If you want to determine the free energy of binding for a specific pose, `Boresch` is likely needed
* For `Boresch`, you have to turn on the restraints over the first few lambda values and leave them on throughout discharging/decoupling, and this requires the ligand never leave the binding site on its own when the restraint is off; for `Harmonic` or `FlatBottom`, you want to keep the restraint on throughout discharging/decoupling

**Comment by Lnaden** [comment]
Here is a preview of the restraint flowchart. This is only a draft so its easy to make changes to it. @jchodera and @andrrizzi I shared this with you on our drive, so you can look at and comment on it directly.

@davidlmobley Any suggestions you or your students have on this are also welcome!

![YANK Restraint Flowchart Draft](https://i.imgur.com/40q5sCm.png)

**Comment by davidlmobley** [comment]
This is extremely helpful in principle, though I wonder if it should be clearly indicated in the flow chart which things have been well validated for the desired use case versus which haven't. For example, do we know that flat bottom is going to be effective in finding multiple binding sites in explicit solvent?

Also, there is no mention of `null` restraints.

I also find it mildly distracting that all the restraints say "always on" except Boresch. Maybe you just want an asterisk for Boresch where you recommend a different protocol for turnign them on?

**Comment by Lnaden** [comment]
> which things have been well validated for the desired use case versus which haven't

I can mark those in an updated draft. Maybe use color coding for blue: validated, red: not. Turn the basic decision boxes into black

> Also, there is no mention of null restraints.

The `null` is the `None` at the top, but I can make that more clear.

> I also find it mildly distracting that all the restraints say "always on"

I'll change that.

Thanks for the feed back!

**Comment by Lnaden** [comment]
All the items on this list have been handled with recent PR's. Closing issue and we can open a new one if more things are found

**Comment by Lnaden** [comment]
The new flowchart is uploaded to the website now as well: http://getyank.org/development/algorithms.html#restraint-selection-flowchart

Its a bit more compact for space and printability if people want that.
